name: mobile
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  url_launcher: ^5.7.10
  jwt_decoder: ^1.0.3
  flutter_secure_storage: ^3.3.5
  intl: ">=0.14.0"
  provider: ^4.3.2+3
  flutter_cache_manager: ^2.1.0
  firebase_admob: ^0.10.3
  curved_navigation_bar: ^0.3.7
  fluttertoast: ^7.1.6
  audioplayers: ^0.15.1
  flutter_localizations:
    sdk: flutter
  http: ^0.12.2
  carousel_slider: ^2.3.1
  flutter_spinkit: ^3.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: IranSans
      fonts:
        - asset: lib/assets/fonts/IranSans.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

